* My GNU Emacs configuration

** TODO these instructions are outdated, I'll update them whenever I can.

For the configuration of Emacs I'm trying out using symlinks instead of copying
files into the right places. For this reason, for now I'm not providing an
automatical way to install everything (this is left to be done in the near
future). The `emacs/init.el` and `emacs/gtkrc` files should be symlinked into
`~/.emacs.d`.

I run GNU Emacs in daemon mode, but I don't use systemd for that. Instead, in
the `i3/config` file you'll see that I'm using `-a ""` as an argument of
`emacsclient`. This instructs `emacsclient` to spawn a new server if there
isn't one already. This means that the first time around it will take some
time, but in the next time everything will be alright.

Last but not least, I'm using my customized `soria` color theme. This theme is
unfortunately not available in any way other than Github. Therefore, you should
clone it yourself in https://github.com/mssola/soria, and add it into
the `~/.emacs.d` directory.

** License

#+BEGIN_SRC text
  Copyright (C) 2014-2017 Miquel Sabaté Solà <mikisabate@gmail.com>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#+END_SRC
